"""empty message

Revision ID: 8e440dbae440
Revises: d1e72e3600bf
Create Date: 2024-01-16 20:14:03.584808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e440dbae440'
down_revision = 'd1e72e3600bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
