"""empty message

Revision ID: d49f9ae53e11
Revises: 8e440dbae440
Create Date: 2024-01-17 22:08:03.905471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49f9ae53e11'
down_revision = '8e440dbae440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_hero_power', ['hero_id', 'power_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_hero_power', type_='unique')

    # ### end Alembic commands ###
